// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: fulcrum.proto

package fulcrum_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_AGREGAR_BASE     Action = 0
	Action_RENOMBRAR_BASE   Action = 1
	Action_ACTUALIZAR_VALOR Action = 2
	Action_BORRAR_BASE      Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "AGREGAR_BASE",
		1: "RENOMBRAR_BASE",
		2: "ACTUALIZAR_VALOR",
		3: "BORRAR_BASE",
	}
	Action_value = map[string]int32{
		"AGREGAR_BASE":     0,
		"RENOMBRAR_BASE":   1,
		"ACTUALIZAR_VALOR": 2,
		"BORRAR_BASE":      3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_fulcrum_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_fulcrum_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{0}
}

type VectorClock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClock) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VectorClock) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *VectorClock) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type CommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commando string `protobuf:"bytes,1,opt,name=commando,proto3" json:"commando,omitempty"`
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{1}
}

func (x *CommandRequest) GetCommando() string {
	if x != nil {
		return x.Commando
	}
	return ""
}

// ip de a quien se conecto por ultima vez, al igual que
// vector de reloj asociado a último cambio
type CommandReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VectorClock *VectorClock `protobuf:"bytes,1,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
}

func (x *CommandReply) Reset() {
	*x = CommandReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReply) ProtoMessage() {}

func (x *CommandReply) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReply.ProtoReflect.Descriptor instead.
func (*CommandReply) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{2}
}

func (x *CommandReply) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type EnemyRequestBroker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commando string `protobuf:"bytes,1,opt,name=commando,proto3" json:"commando,omitempty"`
}

func (x *EnemyRequestBroker) Reset() {
	*x = EnemyRequestBroker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnemyRequestBroker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnemyRequestBroker) ProtoMessage() {}

func (x *EnemyRequestBroker) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnemyRequestBroker.ProtoReflect.Descriptor instead.
func (*EnemyRequestBroker) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{3}
}

func (x *EnemyRequestBroker) GetCommando() string {
	if x != nil {
		return x.Commando
	}
	return ""
}

type EnemyReplyBroker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enemigos    int32        `protobuf:"varint,1,opt,name=enemigos,proto3" json:"enemigos,omitempty"`
	VectorClock *VectorClock `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock,proto3" json:"vector_clock,omitempty"`
}

func (x *EnemyReplyBroker) Reset() {
	*x = EnemyReplyBroker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fulcrum_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnemyReplyBroker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnemyReplyBroker) ProtoMessage() {}

func (x *EnemyReplyBroker) ProtoReflect() protoreflect.Message {
	mi := &file_fulcrum_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnemyReplyBroker.ProtoReflect.Descriptor instead.
func (*EnemyReplyBroker) Descriptor() ([]byte, []int) {
	return file_fulcrum_proto_rawDescGZIP(), []int{4}
}

func (x *EnemyReplyBroker) GetEnemigos() int32 {
	if x != nil {
		return x.Enemigos
	}
	return 0
}

func (x *EnemyReplyBroker) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

var File_fulcrum_proto protoreflect.FileDescriptor

var file_fulcrum_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x22, 0x37, 0x0a, 0x0b, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x7a, 0x22, 0x2c, 0x0a, 0x0e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x22, 0x4f, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x0c, 0x76, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x76, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x30, 0x0a, 0x12, 0x45, 0x6e, 0x65, 0x6d,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x22, 0x6f, 0x0a, 0x10, 0x45, 0x6e,
	0x65, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x65, 0x6e, 0x65, 0x6d, 0x69, 0x67, 0x6f, 0x73, 0x12, 0x3f, 0x0a, 0x0c, 0x76, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x2a, 0x55, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x47, 0x52, 0x45, 0x47, 0x41, 0x52,
	0x5f, 0x42, 0x41, 0x53, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x4e, 0x4f, 0x4d,
	0x42, 0x52, 0x41, 0x52, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x41,
	0x43, 0x54, 0x55, 0x41, 0x4c, 0x49, 0x5a, 0x41, 0x52, 0x5f, 0x56, 0x41, 0x4c, 0x4f, 0x52, 0x10,
	0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x4f, 0x52, 0x52, 0x41, 0x52, 0x5f, 0x42, 0x41, 0x53, 0x45,
	0x10, 0x03, 0x32, 0x65, 0x0a, 0x0f, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x74, 0x65,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x52, 0x0a, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1f, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75,
	0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72,
	0x75, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x7a, 0x0a, 0x14, 0x42, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75,
	0x6d, 0x12, 0x62, 0x0a, 0x16, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x66, 0x75,
	0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6e,
	0x65, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x1a, 0x21, 0x2e, 0x66, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x69, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x52, 0x75, 0x69, 0x7a, 0x41,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6c, 0x61, 0x62, 0x33, 0x2f, 0x66, 0x75, 0x6c, 0x63,
	0x72, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_fulcrum_proto_rawDescOnce sync.Once
	file_fulcrum_proto_rawDescData = file_fulcrum_proto_rawDesc
)

func file_fulcrum_proto_rawDescGZIP() []byte {
	file_fulcrum_proto_rawDescOnce.Do(func() {
		file_fulcrum_proto_rawDescData = protoimpl.X.CompressGZIP(file_fulcrum_proto_rawDescData)
	})
	return file_fulcrum_proto_rawDescData
}

var file_fulcrum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fulcrum_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fulcrum_proto_goTypes = []interface{}{
	(Action)(0),                // 0: fulcrum_service.Action
	(*VectorClock)(nil),        // 1: fulcrum_service.VectorClock
	(*CommandRequest)(nil),     // 2: fulcrum_service.CommandRequest
	(*CommandReply)(nil),       // 3: fulcrum_service.CommandReply
	(*EnemyRequestBroker)(nil), // 4: fulcrum_service.EnemyRequestBroker
	(*EnemyReplyBroker)(nil),   // 5: fulcrum_service.EnemyReplyBroker
}
var file_fulcrum_proto_depIdxs = []int32{
	1, // 0: fulcrum_service.CommandReply.vector_clock:type_name -> fulcrum_service.VectorClock
	1, // 1: fulcrum_service.EnemyReplyBroker.vector_clock:type_name -> fulcrum_service.VectorClock
	2, // 2: fulcrum_service.InformanteWrite.ExecuteCommand:input_type -> fulcrum_service.CommandRequest
	4, // 3: fulcrum_service.BrokerRequestFulcrum.EnemyInformationBroker:input_type -> fulcrum_service.EnemyRequestBroker
	3, // 4: fulcrum_service.InformanteWrite.ExecuteCommand:output_type -> fulcrum_service.CommandReply
	5, // 5: fulcrum_service.BrokerRequestFulcrum.EnemyInformationBroker:output_type -> fulcrum_service.EnemyReplyBroker
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fulcrum_proto_init() }
func file_fulcrum_proto_init() {
	if File_fulcrum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fulcrum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorClock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnemyRequestBroker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fulcrum_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnemyReplyBroker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fulcrum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fulcrum_proto_goTypes,
		DependencyIndexes: file_fulcrum_proto_depIdxs,
		EnumInfos:         file_fulcrum_proto_enumTypes,
		MessageInfos:      file_fulcrum_proto_msgTypes,
	}.Build()
	File_fulcrum_proto = out.File
	file_fulcrum_proto_rawDesc = nil
	file_fulcrum_proto_goTypes = nil
	file_fulcrum_proto_depIdxs = nil
}
